{
 "title": "Roborock Olga",
 "time": { "from": "now-30d", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Olga batteri",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT last(\"value\") FROM \"%\" WHERE \"entity_id\"='olga_batteri'"
    }
   ]
  },
  {
   "title": "Olga status",
   "type": "state-timeline",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "SELECT last(\"state\") FROM \"sensor.olga_status\" WHERE \"entity_id\"='olga_status'"
    }
   ]
  },
  {
   "title": "Olga stadar",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT last(\"value\") FROM \"binary_sensor.olga_stadar\" WHERE \"entity_id\"='olga_stadar'"
    }
   ]
  },
  {
   "title": "Olga laddning",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "SELECT mean(\"value\") FROM \"binary_sensor.olga_laddning\" WHERE \"entity_id\"='olga_laddning' AND $timeFilter GROUP BY time($__interval) fill(previous)"
    }
   ]
  },
  {
   "title": "Olga stadad area",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "areaM2" } },
   "targets": [
    {
     "query": "SELECT mean(\"value\") FROM \"m²\" WHERE \"entity_id\"='olga_stadad_area' AND time > now() - 30d GROUP BY time(5m) fill(previous)"
    }
   ]
  },
  {
   "title": "Olga total stadtid",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "query": "SELECT mean(\"value\") FROM \"h\" WHERE \"entity_id\"='olga_total_stadtid' AND time > now() - 30d GROUP BY time(5m) fill(previous)"
    }
   ]
  },
  {
   "title": "Olga totalt antal stadningar",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "SELECT mean(\"value\") FROM \"sensor.olga_totalt_antal_stadningar\" WHERE \"entity_id\"='olga_totalt_antal_stadningar' AND time > now() - 30d GROUP BY time(5m) fill(previous)"
    }
   ]
  },
  {
   "title": "Olga totalt stadad area",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "areaM2" } },
   "targets": [
    {
     "query": "SELECT mean(\"value\") FROM \"m²\" WHERE \"entity_id\"='olga_totalt_stadad_area' AND time > now() - 30d GROUP BY time(5m) fill(previous)"
    }
   ]
  }
 ]
}