{
 "title": "Temperaturer och Luftfuktighet Peter",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Temp Tvattstuga Nu",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT last(\"value\") FROM \"°C\" WHERE \"entity_id\"='dehumidifier_20l_temperatur'"
    }
   ]
  },
  {
   "title": "Luftfuktighet Tvattstuga Nu",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT last(\"value\") FROM \"%\" WHERE \"entity_id\"='dehumidifier_20l_luftfuktighet'"
    }
   ]
  },
  {
   "title": "Ute Temp Nu",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT last(\"value\") FROM \"°C\" WHERE \"entity_id\"='ute_temp_temperatur'"
    }
   ]
  },
  {
   "title": "Ute Luftfuktighet Nu",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT last(\"value\") FROM \"%\" WHERE \"entity_id\"='ute_temp_luftfuktighet'"
    }
   ]
  },
  {
   "title": "Temp Tvattstuga",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "alias": "$tag_entity_id",
     "query": "SELECT mean(\"value\") FROM \"°C\" WHERE \"entity_id\"='dehumidifier_20l_temperatur' AND time > now() - 24h GROUP BY time(1m) fill(previous)"
    }
   ]
  },
  {
   "title": "Luftfuktighet Tvattstuga",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "$tag_entity_id",
     "query": "SELECT mean(\"value\") FROM \"%\" WHERE \"entity_id\"='dehumidifier_20l_luftfuktighet' AND time > now() - 24h GROUP BY time(1m) fill(previous)"
    }
   ]
  },
  {
   "title": "Ute Temp",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "SELECT mean(\"value\") FROM \"°C\" WHERE \"entity_id\"='ute_temp_temperatur' AND time > now() - 24h GROUP BY time(1m) fill(previous)"
    }
   ]
  },
  {
   "title": "Luftfuktighet Ute",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "SELECT mean(\"value\") FROM \"%\" WHERE \"entity_id\"='ute_temp_luftfuktighet' AND time > now() - 24h GROUP BY time(1m) fill(previous)"
    }
   ]
  },
  {
   "title": "Temp Matförråd Nu",
   "type": "stat",
   "gridPos": { "x": 0, "y": 31, "w": 12, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT last(\"value\") AS \"value\" FROM \"C\" WHERE \"entity_id\"='matforradet_temperatur' AND $timeFilter"
    }
   ]
  }
 ]
}