{
 "title": "Temperaturer och Luftfuktighet",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Temp Tvättstuga",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT last(\"value\") FROM \"°C\" WHERE \"entity_id\"='dehumidifier_20l_temperatur'"
    }
   ]
  },
  {
   "title": "Luftfuktighet Tvättstuga",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT last(\"value\") FROM \"%\" WHERE \"entity_id\"='dehumidifier_20l_luftfuktighet'"
    }
   ]
  },
  {
   "title": "Temp Tvättstuga över tid",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "alias": "$tag_entity_id",
     "query": "SELECT mean(\"value\") FROM \"°C\" WHERE \"entity_id\"='dehumidifier_20l_temperatur' AND time > now() - 24h GROUP BY time(1m) fill(previous)"
    }
   ]
  },
  {
   "title": "Luftfuktighet Tvättstuga över tid",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "$tag_entity_id",
     "query": "SELECT mean(\"value\") FROM \"%\" WHERE \"entity_id\"='dehumidifier_20l_luftfuktighet' AND time > now() - 24h GROUP BY time(1m) fill(previous)"
    }
   ]
  },
  {
   "title": "Ute Temp över tid",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "SELECT mean(\"value\") FROM \"°C\" WHERE \"entity_id\"='ute_temp_temperatur' AND time > now() - 24h GROUP BY time(1m) fill(previous)"
    }
   ]
  },
  {
   "title": "Ute Temp Nu",
   "type": "stat",
   "gridPos": { "x": 12, "y": 0, "w": 6, "h": 4 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT last(\"value\") FROM \"°C\" WHERE \"entity_id\"='ute_temp_temperatur'"
    }
   ]
  },
  {
   "title": "Ute Luftfuktighet Nu",
   "type": "stat",
   "gridPos": { "x": 18, "y": 0, "w": 6, "h": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT last(\"value\") FROM \"%\" WHERE \"entity_id\"='ute_temp_luftfuktighet'"
    }
   ]
  },
  {
   "title": "Ute Luftfuktighet över tid",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "SELECT mean(\"value\") FROM \"%\" WHERE \"entity_id\"='ute_temp_luftfuktighet' AND time > now() - 24h GROUP BY time(1m) fill(previous)"
    }
   ]
  }
 ]
}